config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :posts
  resources :comments do
  	collection do
  	  get '/:post_id', to: 'comments#index_posts'
  	end
  end
  devise_for :users

  post '/login', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post 
	# belongs_to :user 
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  #before_action :configure_devise_params, if: :devise_controller?

  #def configure_devise_params
  #	devise_paramater_sanitizer.permit(:sign_up) do |user|
  #		user.permit(:name, :email, :password, :password_confirmation)
  #	end
  #end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		post = Post.find(params[:post_id])
		render json: { data: post.comments }
	end

	def index_posts
		post = Post.find(params[:post_id])
		render json: { data: post.comments }
	end

	#def new

	#end

	def create
		#render plain: params[	:post].inspect
		@comment = Comment.new comment_params
		if @comment.save
			render json: @comment
		else
			render json: @comment.errors, status: 400
		end
	end

	def show
		@comments = Comment.find params[:id]
		render json:@comments
	end

	def comment_params
		params.require(:comment).permit(:post_id, :user_id,:content)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def index
		@posts = Post.all
		render json:@posts
	end

	def new

	end

	def create
		#render plain: params[:post].inspect
		@post = Post.new post_params
		@post.save

		redirect_to @post

	end

	def show
		@post = Post.find params[:id]
	end

	def post_params
		params.require(:post).permit(:title,:content,:image)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		email = params[:email]
		user = User.find_by(email: email)

		if user.valid_password? params[:password]
			render json: user, status: :ok
		else
			render json: { error: 'asfasdf' }, status: 404
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<%- if user_signed_in? %>
  	<h1>PowerCar</h1>
	<p>Welcome, <%=  current_user.email %></p>
<% else %>
  	<h1>PowerCar</h1>
	<p>Welcome to our platform</p> 		
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prmysql3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <ul class="nav justify-content-end">
  	<%- if user_signed_in? %>
  		<li class="nav-item">
  			<%= link_to 'Salir', destroy_user_session_path, method: :delete %>
  		</li>
  	<% else %>
  		<li class="nav-item">
  			<%= link_to 'Log in', new_user_session_path %>
  		</li>
  		<li class="nav-item">
  			<%= link_to 'Register', new_user_registration_path %>
  		</li>
  	<% end %>
  </ul>

  <body>
  	<div class="container">
  		<p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p>
    	<%= yield %>
	</div>
  </body>
</html>

app/views/posts/_post.html.erb
<%= post.title %><br>
<%= post.content %><br><br>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<div>
	<h1>Discuss your idea</h1>
	<%= form_for :post, url: posts_path do |f| %>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
		<%= f.label :content %><br>
		<%= f.text_field :content %><br>
		<%= f.label :image %><br>
		<%= f.text_field :image %><br><br>

		<%= f.submit %>
	<% end %>
</div>

app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.content %>